project:
  type: website

website:
  title: "Zach Duey"
  google-analytics: "G-317KRPWML8"
  twitter-card: true
  site-url: https://www.zduey.github.io
  description: "Personal website for Zach Duey"
  navbar:
    right:
      - href: about.qmd
        text: About
      - href: blog.qmd
        text: Blog 
      - text: Projects
        menu:
          - text: Master's Thesis
            href: https://zduey.github.io/revisiting-shapley-values
      - icon: github
        href: https://github.com/zduey
      - icon: twitter
        href: https://twitter.com/z_duey
      - icon: linkedin
        href: https://linkedin.com/in/zachduey 
      - icon: rss
        href: index.xml
  page-footer:
    left: "Copyright 2023, Zach Duey"
    right:
      - icon: github
        href: https://github.com/zduey
      - icon: twitter
        href: https://twitter.com/z_duey
      - icon: linkedin
        href: https://linkedin.com/in/zachduey 
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css

execute:
  freeze: auto
